name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  LILYPOND_VERSION: 2.22.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build the Docker image
      run: docker build --build-arg "LILYPOND_VERSION=${LILYPOND_VERSION}" . --file Dockerfile --tag yatjf_jam_book-lilypond-${LILYPOND_VERSION}

    - name: Build the book
      run: make docker_build IMAGE_TAG=yatjf_jam_book-lilypond-${LILYPOND_VERSION}

    - name: Make book index.html
      working-directory: output/
      run: |
        (
            echo "<html><head><title>yet another trad jazz fakebook</title></head><body><br/>"
            echo "<h1><a href=\"https://github.com/vault103/yet_another_trad_jazz_fakebook\">yet another trad jazz fakebook</a></h1><br/><br/>"
            for file in *.pdf; do
                part_name=$(echo "$file" | perl -pe 's/yatjf_jam_book-//; s/\.pdf//; s/_/ /g')
                echo "<a href=\"$file\">$part_name"</a><br/>"
            done
            echo "</body></html>"
        ) > index.html
    - name: Upload book
      uses: actions/upload-artifact@v4
      with:
        name: jam_book
        path: "output/*"
        if-no-files-found: error
